"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def evenFibonacci():
    first = 1
    second = 2
    evenTerms = [2]
    total = 0
    notFinished = True
    while (notFinished):
        sum = first + second
        if (sum % 2 == 0):
            evenTerms.append(sum)
        if (sum > 4000000):
            notFinished = False
        first = second
        second = sum
    for item in evenTerms:
        total = total + item
    return total

def main():
    print(evenFibonacci())

if __name__ == "__main__":
    main()